=== hrishav2004/AI-Powered-Cloud-Cost-Optimizer-LLM-Driven-/utils/schemas/project_profile_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["name","budget_inr_per_month","description","tech_stack","non_functional_requirements"],
  "properties": {
    "name": {
        "type": ["string","null"]
    },
    "budget_inr_per_month": {
        "type": ["number","null"],
        "minimum": 0
    },
    "description": {
        "type": ["string","null"]
    },
    "tech_stack": {
      "type": "object",
      "required": ["backend","database","storage","monitoring","analytics"],
      "properties": {
        "backend": {
            "type": ["string","null"]
        },
        "database": {
            "type": ["string","null"]
        },
        "storage": {
            "type": ["string","null"]
        },
        "monitoring": {
            "type": ["string","null"]
        },
        "analytics": {
            "type": ["string","null"]
        }
      }
    },
    "non_functional_requirements": {
      "type": "array",
      "items": {
        "type": "string"
        }
    }
  },
  "additionalProperties": true
}

=== hrishav2004/AI-Powered-Cloud-Cost-Optimizer-LLM-Driven-/pipeline_output/project_profile.json
{
  "name": "AI-powered Community Platform",
  "budget_inr_per_month": 40000,
  "description": "An AI-powered community platform providing a space for Machine Learning enthusiasts to connect, chat, and learn together.",
  "tech_stack": {
    "frontend": "Angular",
    "backend": "Node.js",
    "database": "MongoDB",
    "storage": null,
    "proxy": "Nginx",
    "hosting": "Azure",
    "api": "Hugging Face Inference API",
    "monitoring": null,
    "analytics": null
  },
  "non_functional_requirements": [
    "Scalability",
    "Cost efficiency",
    "Performance"
  ]
}
